### ISSUE TITLE
Broken link in paper.md

### ISSUE THREAD

**Issue by amoeba** [arcaravaggi/remBoot#13]
Hey @arcaravaggi, I was just checking the links in the JOSS `paper.md` and found the link in this reference isn't working:

> Oliveira-Santos, L.G.R., Zucco, C.A., Antunes, P.C. and Crawshaw, P.G. (2010). Is it possible to individually identify mammals with no natural markings using camera-traps? A controlled case-study with lowland tapirs. Mamm Biol. 75, 375 – 378. DOI: 10.1016/j.mambio.2009.08.005

Haven't looked at why but I'm guessing there is a slight typo.

**Comment by arcaravaggi** [comment]
Thanks, @amoeba. I'd only put the doi into the parentheses. The link is now functioning correctly.
