### ISSUE TITLE
I always fail when trying to call data. It said data set not found. But, if I call table hDat from exercise, it succeed. Would you please help about this issue? Thanks

### ISSUE THREAD

**Issue by arcaravaggi** [arcaravaggi/remBoot#23]
I always fail when trying to call data. It said data set not found. But, if I call table hDat from exercise, it succeed. Would you please help about this issue? Thanks

_Originally posted by @yudhihariyawan in https://github.com/arcaravaggi/remBoot/issues/17#issuecomment-455049113_

**Comment by arcaravaggi** [comment]
Hi @yudhihariyawan . Could you please provide the code you are using and the exact error?

**Comment by yudhihariyawan** [comment]
Dear Anthony,

Thank you for your fast response.

I use exactly the same codes you provided in this link https://github.com/arcaravaggi/remBoot

And this is the copy of process (with error message)
=================================================
> library (remBoot)
> setwd ("C:/7_REM")
> data (Banteng2018B)
Warning message:
In data(Banteng2018B) : data set ‘Banteng2018B’ not found
=================================================

I tried to cheat the file through copying all my data to file hDat and save in that file. However, when I tried to check the content of hDat using grpDat, the content was still refer to original file.

Your help is very useful. We are trying to use this package for analyzing Banteng density in Baluran National Park, East Java, Indonesia.

Thank you,
Wahyudi



Sent from Mail for Windows 10

**Comment by arcaravaggi** [comment]
Thanks for the detail. Could you please confirm that you are loading your data into R in the first instance, e.g. `dat <- read.csv("data.csv")`

**Comment by yudhihariyawan** [comment]
No, I did not . Actually, I was thinking that loading data into R is using data (files.txt). Please correct me if I am wrong. Thanks

Sent from Mail for Windows 10

**Comment by arcaravaggi** [comment]
You can do that, certainly. Either way, it looks like the reason that you're not able to read your data is because you've not actually loaded it into R yet. The `hDat` dataframe is supplied with the package and is called by using `data(hDat)`. To use your data, you should first load it, like this (if using a text file):

`my_data <- read.delim("mytextfile.txt")`

Where you replace "my_data" and "mytextfile.txt" with the names that are appropriate to your work. From there, ignore the `data()` argument in the examples. Everything else should work.

**Comment by yudhihariyawan** [comment]
It works!! Thank you for your help!

Best

Sent from Mail for Windows 10

**Comment by arcaravaggi** [comment]
No problem at all. Let me know if you have any other issues.

**Comment by arcaravaggi** [comment]
No problem at all. Let me know if you have any other issues.
