### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by sckott** [arcaravaggi/remBoot#4]
- on running check 

```r
* creating vignettes ... ERROR
Quitting from lines 45-48 (remBoot.Rmd)
Error: processing vignette 'remBoot.Rmd' failed with diagnostics:
object 'hDat' not found
```

- `ggplot2` should be in Suggests since its used in the vignette

- global variables

```r
N  checking R code for possible problems
   boot_sd: no visible binding for global variable ‘nboots’
   boot_sd: no visible binding for global variable ‘tm’
   boot_sd: no visible binding for global variable ‘v’
   remBoot: no visible binding for global variable ‘sd’
   remBoot: no visible binding for global variable ‘quantile’
   Undefined global functions or variables:
     nboots quantile sd tm v
   Consider adding
     importFrom("stats", "quantile", "sd")
   to your NAMESPACE file.
```

- looks like `remDat` is undocumented

- undocumented parameters

```r
Undocumented arguments in documentation object 'boot_sd'
     ‘x’

   Undocumented arguments in documentation object 'remBoot'
     ‘.df’

   Undocumented arguments in documentation object 'res_dat'
     ‘.df’
```

- in `boot_sd` eg. `grpDat` object not found

**Comment by sckott** [comment]
I'd add URL and BugReports fields  to DESCRIPTION so users know how to get in touch with you

a good thing to do is run `goodpractice::gp()` on your package - will point out various things that are considered best practice

**Comment by timcdlucas** [comment]
Hi,

The "no visible binding stuff" is what we were just talking about on twitter. Everything a function uses, should either be defined internally or given as an argument.

```
inner <- function(x, y, z){
 x + y +z
}

outer <- function(a, b, c){
  output <- inner(a, b, c)
}
```

NOT


```
inner <- function(){
 x + y +z
}

outer <- function(x, y, z){
  output <- inner()
}
```

This makes it unambiguous *which* `x` it should use.

For example:

```
x <- 2

outer(9, 9, 9)
```

If your code is defined as in the second example, which `x` does `inner` use? `x = 2` from the global environment or `x = 9` for the argument to `outer`.

Hope that is clear. It also makes it easier to read the code. When I was reading `remBoot`, I couldn't see where `tm` was used without searching through the whole repo.

Happy to explain more if needed!

**Comment by arcaravaggi** [comment]
Thanks for the feedback, both. I've corrected some of the check errors, but several are confusing as the code works. I've added a URL to the DESCRIPTION file, but I don't have a URL for BugReports, yet.

Thanks for the advice re: functions, too. I'll incorporate this advice as I develop the package.

**Comment by sckott** [comment]
for bugreports, would  https://github.com/arcaravaggi/remBoot/issues work?

**Comment by arcaravaggi** [comment]
I'm finding way with git at the moment. If that's a viable option,, I'll use it, no problem.

**Comment by sckott** [comment]
i think that’s' generally what people do, e.g, https://cran.rstudio.com/web/packages/jsonlite/

**Comment by arcaravaggi** [comment]
Thanks. I've added it to the DESCRIPTION.
